"""
Markdown documentation generator.

Every document — pipeline, notebook, or dataflow — produces the same five sections:

  ## Purpose
  ## Flow
  ## Business Goal
  ## Data Quality & Alerts
  ## Column Lineage

Each section is generated by a dedicated LLM call so context stays focused.
The content summary (_pipeline_content / _notebook_content / _dataflow_content) is
built once and reused across all five calls for the same document.
"""

from __future__ import annotations

import textwrap
from datetime import datetime
from pathlib import Path

from agent.ai.base_client import BaseLLMClient
from agent.ai.utils import _summarise_props
from agent.config import ACTIVITY_TYPE_LABELS, DATAFLOW_ACTIVITY_TYPES, DEPENDENCY_CONDITION_LABELS
from agent.enrichers.ticket_enricher import fetch_ticket_context
from agent.parsers.dataflow_parser import ParsedDataflow
from agent.parsers.notebook_parser import ParsedNotebook
from agent.parsers.pipeline_parser import ParsedPipeline, PipelineActivity
from agent.parsers.powerautomate_parser import ParsedPowerAutomateFlow

SECTIONS = ["Purpose", "Flow", "Business Goal", "Data Quality & Alerts", "Column Lineage"]

_FLOW_FALLBACK_CHARS = 1500


def _build_purpose_content(artifact_name: str, purpose_content: str, flow_content: str) -> str:
    """Return purpose content enriched with ticket/PR context if available.

    If linked work items or pull requests are found for *artifact_name*, they
    are prepended so the LLM can ground the purpose in real business intent.
    When nothing is found, the data-flow content is appended as a fallback so
    the LLM can infer the purpose from what the artifact actually does.
    """
    ticket_ctx = fetch_ticket_context(artifact_name)
    if ticket_ctx:
        return f"Linked work items and pull requests:\n{ticket_ctx}\n\n{purpose_content}"
    return (
        f"{purpose_content}\n\n"
        f"Data flow context (use this to infer the business purpose if the above is insufficient):\n"
        f"{flow_content[:_FLOW_FALLBACK_CHARS]}"
    )


# ---------------------------------------------------------------------------
# Public generators
# ---------------------------------------------------------------------------

def generate_pipeline_doc(
    pipeline: ParsedPipeline,
    notebook_map: dict[str, ParsedNotebook],
    client: BaseLLMClient,
    dataflow_map: dict[str, ParsedDataflow] | None = None,
) -> str:
    dataflow_map = dataflow_map or {}
    doc_group = pipeline.name
    c = _pipeline_contents(pipeline, notebook_map, dataflow_map)
    purpose_content = _build_purpose_content(pipeline.name, c["purpose"], c["relationships"])

    parts = [
        f"# {pipeline.name}",
        _meta_block("Pipeline", pipeline.source_path),
        f"## Purpose\n\n{client.section_purpose(pipeline.name, purpose_content, doc_group)}",
        f"## Flow\n\n{client.section_flow(pipeline.name, c['relationships'], doc_group)}",
        f"## Business Goal\n\n{client.section_business_goal(pipeline.name, c['goal'], doc_group)}",
        f"## Data Quality & Alerts\n\n{client.section_data_quality(pipeline.name, c['quality'], doc_group)}",
        f"## Column Lineage\n\n{client.section_column_lineage(pipeline.name, _lineage_content(pipeline, notebook_map, dataflow_map), doc_group)}",
        "\n---",
        f"*Documentation generated on {datetime.now().strftime('%Y-%m-%d')} "
        f"from `{pipeline.source_path.name}`.*",
    ]
    return "\n\n".join(parts)


def generate_notebook_doc(notebook: ParsedNotebook, client: BaseLLMClient) -> str:
    doc_group = notebook.name
    c = _notebook_contents(notebook)
    purpose_content = _build_purpose_content(notebook.name, c["purpose"], c["relationships"])

    parts = [
        f"# {notebook.name}",
        _meta_block("Data Process", notebook.source_path),
        f"## Purpose\n\n{client.section_purpose(notebook.name, purpose_content, doc_group)}",
        f"## Flow\n\n{client.section_flow(notebook.name, c['relationships'], doc_group)}",
        f"## Business Goal\n\n{client.section_business_goal(notebook.name, c['goal'], doc_group)}",
        f"## Data Quality & Alerts\n\n{client.section_data_quality(notebook.name, c['quality'], doc_group)}",
        f"## Column Lineage\n\n{client.section_column_lineage(notebook.name, _lineage_content_notebook(notebook), doc_group)}",
        "\n---",
        f"*Documentation generated on {datetime.now().strftime('%Y-%m-%d')} "
        f"from `{notebook.source_path.name}`.*",
    ]
    return "\n\n".join(parts)


def generate_dataflow_doc(dataflow: ParsedDataflow, client: BaseLLMClient) -> str:
    doc_group = dataflow.name
    c = _dataflow_contents(dataflow)
    purpose_content = _build_purpose_content(dataflow.name, c["purpose"], c["relationships"])

    parts = [
        f"# {dataflow.name}",
        _meta_block("Dataflow Gen2", dataflow.source_path),
        f"## Purpose\n\n{client.section_purpose(dataflow.name, purpose_content, doc_group)}",
        f"## Flow\n\n{client.section_flow(dataflow.name, c['relationships'], doc_group)}",
        f"## Business Goal\n\n{client.section_business_goal(dataflow.name, c['goal'], doc_group)}",
        f"## Data Quality & Alerts\n\n{client.section_data_quality(dataflow.name, c['quality'], doc_group)}",
        f"## Column Lineage\n\n{client.section_column_lineage(dataflow.name, _lineage_content_dataflow(dataflow), doc_group)}",
        "\n---",
        f"*Documentation generated on {datetime.now().strftime('%Y-%m-%d')} "
        f"from `{dataflow.source_path.name}`.*",
    ]
    return "\n\n".join(parts)


def generate_powerautomate_doc(flow: ParsedPowerAutomateFlow, client: BaseLLMClient) -> str:
    doc_group = flow.name
    c = _powerautomate_contents(flow)
    purpose_content = _build_purpose_content(flow.name, c["purpose"], c["relationships"])

    parts = [
        f"# {flow.name}",
        _meta_block("Power Automate Flow", flow.source_path),
        f"## Purpose\n\n{client.section_purpose(flow.name, purpose_content, doc_group)}",
        f"## Flow\n\n{client.section_flow(flow.name, c['relationships'], doc_group)}",
        f"## Business Goal\n\n{client.section_business_goal(flow.name, c['goal'], doc_group)}",
        f"## Data Quality & Alerts\n\n{client.section_data_quality(flow.name, c['quality'], doc_group)}",
        f"## Column Lineage\n\n{client.section_column_lineage(flow.name, _lineage_content_powerautomate(flow), doc_group)}",
        "\n---",
        f"*Documentation generated on {datetime.now().strftime('%Y-%m-%d')} "
        f"from `{flow.source_path.name}`.*",
    ]
    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# Public helpers used by main.py
# ---------------------------------------------------------------------------

def get_linked_notebooks(
    pipeline: ParsedPipeline,
    notebook_map: dict[str, ParsedNotebook],
) -> set[str]:
    """Return the names of all notebooks linked to any activity in *pipeline*."""
    linked: set[str] = set()
    for activity in pipeline.activities:
        nb = _resolve_notebook(activity, notebook_map)
        if nb:
            linked.add(nb.name)
    return linked


def get_linked_dataflows(
    pipeline: ParsedPipeline,
    dataflow_map: dict[str, ParsedDataflow],
) -> set[str]:
    """Return names of all dataflows referenced by activities in *pipeline*."""
    linked: set[str] = set()
    for activity in pipeline.activities:
        df = _resolve_dataflow(activity, dataflow_map)
        if df:
            linked.add(df.name)
    return linked


# ---------------------------------------------------------------------------
# Section-specific content builders
# ---------------------------------------------------------------------------

def _pipeline_contents(
    pipeline: ParsedPipeline,
    notebook_map: dict[str, ParsedNotebook],
    dataflow_map: dict[str, ParsedDataflow] | None = None,
) -> dict[str, str]:
    """Return a dict of tailored content strings, one per document section."""
    dataflow_map = dataflow_map or {}
    ordered = pipeline.ordered_activities()
    activity_labels = [
        f"{a.name} ({ACTIVITY_TYPE_LABELS.get(a.activity_type, a.activity_type)})"
        for a in ordered
    ]
    description = pipeline.description or ""
    params = ", ".join(f"{p.name}" for p in pipeline.parameters) if pipeline.parameters else ""

    # Linked notebooks — name + section headings
    notebook_refs: list[str] = []
    for a in ordered:
        nb = _resolve_notebook(a, notebook_map)
        if nb:
            headings = ", ".join(s.heading for s in nb.sections)
            notebook_refs.append(f"{nb.name} (sections: {headings})")

    # Code from linked notebooks — for quality and what-it-does
    notebook_code = ""
    for a in ordered:
        nb = _resolve_notebook(a, notebook_map)
        if nb:
            notebook_code += nb.all_code[:1500] + "\n"

    # Linked dataflows — query names + M-code excerpt
    dataflow_refs: list[str] = []
    dataflow_mcode = ""
    for a in ordered:
        df = _resolve_dataflow(a, dataflow_map)
        if df:
            dataflow_refs.append(f"{df.name} (queries: {', '.join(df.query_names)})")
            dataflow_mcode += df.all_mcode[:1500] + "\n"

    # Control / fail / webhook / web activities — signal quality checks and external alerts
    quality_activities = [
        f"{a.name} ({ACTIVITY_TYPE_LABELS.get(a.activity_type, a.activity_type)}): {_summarise_props(a.type_properties)}"
        for a in ordered
        if a.activity_type in ("IfCondition", "Fail", "WebHook", "Filter", "Until", "Switch", "Web")
    ]

    # External connections — bronze activities
    sources = [
        f"{a.name}: {_summarise_props(a.type_properties)}"
        for a in ordered
        if a.activity_type in ("Copy", "Web", "WebHook", "Lookup", "GetMetadata")
    ]

    all_refs = notebook_refs + dataflow_refs
    all_code = (notebook_code + dataflow_mcode).strip()

    return {
        "purpose": f"Pipeline: {pipeline.name}\nDescription: {description}\nSteps: {', '.join(activity_labels)}",
        "relationships": (
            f"Pipeline: {pipeline.name}\n"
            + (f"External data sources: {'; '.join(sources)}\n" if sources else "")
            + (f"Linked processes: {'; '.join(all_refs)}\n" if all_refs else "")
            + (f"Input parameters: {params}\n" if params else "")
        ),
        "goal": f"Pipeline: {pipeline.name}\nDescription: {description}\nSteps: {', '.join(activity_labels)}",
        "quality": (
            f"Pipeline: {pipeline.name}\n"
            + (f"Control and error steps: {'; '.join(quality_activities)}\n" if quality_activities else "")
            + (f"Error and alert signals:\n{_extract_alert_signals(all_code)}\n\n" if all_code else "")
            + (f"Full code excerpt:\n{all_code[:2000]}" if all_code else "")
        ),
    }


def _extract_alert_signals(code: str) -> str:
    """Return lines from *code* that contain error-raising or notification patterns.

    Captures raise/except statements, logging calls, and external notification
    patterns (email, webhook, Teams, Slack, monitoring APIs) with one line of
    surrounding context so the LLM has enough to interpret each signal.
    """
    keywords = (
        "raise ", "except ", "exception",
        "logging.", "logger.", "log.error", "log.warn", "log.critical",
        "print(",
        "email", "smtp", "sendmail", "send_mail", "send_email",
        "notify", "notification", "alert",
        "webhook", "teams", "slack",
        "requests.post", "requests.get", "http",
    )
    lines = code.splitlines()
    collected: list[str] = []
    seen: set[int] = set()
    for i, line in enumerate(lines):
        lower = line.lower()
        if any(kw in lower for kw in keywords):
            for idx in range(max(0, i - 1), min(len(lines), i + 2)):
                if idx not in seen:
                    collected.append(lines[idx])
                    seen.add(idx)
            collected.append("…")
    return "\n".join(collected[:60])  # cap to avoid prompt bloat


def _notebook_contents(notebook: ParsedNotebook) -> dict[str, str]:
    """Return a dict of tailored content strings, one per document section."""
    headings = ", ".join(s.heading for s in notebook.sections)
    description = notebook.description or ""
    code = notebook.all_code
    alert_signals = _extract_alert_signals(code)

    return {
        "purpose": f"Process: {notebook.name}\nDescription: {description}\nSections: {headings}",
        "relationships": (
            f"Process: {notebook.name}\nDescription: {description}\nSections: {headings}"
        ),
        "goal": f"Process: {notebook.name}\nDescription: {description}\nSections: {headings}",
        "quality": (
            f"Process: {notebook.name}\nSections: {headings}\n"
            + (f"Error and alert signals:\n{alert_signals}\n\n" if alert_signals else "")
            + f"Full code excerpt:\n{code[:2500]}"
        ),
    }


_MCODE_PREAMBLE = (
    "The following is Power Query M-code from a Microsoft Fabric Dataflow Gen2. "
    "Each named block is a query (table) in the dataflow. "
    "Queries build on each other: earlier queries are raw sources (bronze), "
    "later ones apply transformations (silver) or produce the final output (gold).\n\n"
)


def _dataflow_contents(dataflow: ParsedDataflow) -> dict[str, str]:
    """Return a dict of tailored content strings, one per document section."""
    description = dataflow.description or ""
    query_names = ", ".join(dataflow.query_names)
    mcode = dataflow.all_mcode

    base = f"{_MCODE_PREAMBLE}Dataflow: {dataflow.name}\nDescription: {description}\nQueries: {query_names}\n\n"

    return {
        "purpose": base + mcode[:2000],
        "relationships": base + mcode[:2000],
        "goal":    base + mcode[:2000],
        "quality": (
            base
            + "Focus on filter steps, error handling, null checks, type validations, and any error or notification expressions.\n\n"
            + mcode[:3000]
        ),
    }


_PA_PREAMBLE = (
    "The following describes a Microsoft Power Automate flow. "
    "Power Automate connects apps and services to automate business processes. "
    "A trigger starts the flow; actions are the steps executed in response.\n\n"
)


def _powerautomate_contents(flow: ParsedPowerAutomateFlow) -> dict[str, str]:
    """Return a dict of tailored content strings, one per document section."""
    description = flow.description or ""
    trigger_text = f"Trigger: {flow.trigger_summary}\n" if flow.trigger_summary else ""
    conn_text = f"Connected services: {', '.join(flow.connections)}\n" if flow.connections else ""

    # Group actions by type for quality/error analysis
    control_types = {"condition", "switch", "terminate", "filter", "scope", "foreach", "apply_to_each", "do_until"}
    control_actions = [
        f"{a.name} ({a.type})"
        for a in flow.actions
        if a.type.lower() in control_types
    ]
    all_actions = ", ".join(a.name for a in flow.actions)

    base = f"{_PA_PREAMBLE}Flow: {flow.name}\nDescription: {description}\n"
    relationships = base + trigger_text + (f"Actions: {all_actions}\n" if all_actions else "") + conn_text

    return {
        "purpose": relationships,
        "relationships": relationships,
        "goal": relationships,
        "quality": (
            base
            + trigger_text
            + (f"Control and branching steps: {', '.join(control_actions)}\n" if control_actions else "")
            + (f"All actions: {all_actions}\n" if all_actions else "")
            + conn_text
            + "Focus on error handling, condition checks, and failure branches (Terminate actions, Condition steps)."
        ),
    }


# ---------------------------------------------------------------------------
# Lineage content builders
# ---------------------------------------------------------------------------

def _lineage_content(
    pipeline: ParsedPipeline,
    notebook_map: dict[str, ParsedNotebook],
    dataflow_map: dict[str, ParsedDataflow] | None = None,
) -> str:
    """Collect all notebook and dataflow code from a pipeline for column lineage extraction."""
    dataflow_map = dataflow_map or {}
    ordered = pipeline.ordered_activities()
    parts: list[str] = [
        f"Pipeline: {pipeline.name}",
        f"Description: {pipeline.description or '(none)'}",
        "",
    ]
    has_artifacts = False
    for activity in ordered:
        nb = _resolve_notebook(activity, notebook_map)
        if nb:
            parts.append(f"--- Notebook: {nb.name} (activity: {activity.name}) ---")
            parts.append(nb.all_code[:3000])
            parts.append("")
            has_artifacts = True
        df = _resolve_dataflow(activity, dataflow_map)
        if df:
            parts.append(f"--- Dataflow: {df.name} (activity: {activity.name}) ---")
            parts.append(_MCODE_PREAMBLE + df.all_mcode[:3000])
            parts.append("")
            has_artifacts = True
    if not has_artifacts:
        for activity in ordered:
            if activity.description:
                parts.append(f"Activity '{activity.name}': {activity.description}")
    return "\n".join(parts)


def _lineage_content_notebook(notebook: ParsedNotebook) -> str:
    """Return notebook code for column lineage extraction."""
    parts = [
        f"Notebook: {notebook.name}",
        f"Description: {notebook.description or '(none)'}",
        "",
        notebook.all_code,
    ]
    return "\n".join(parts)


def _lineage_content_powerautomate(flow: ParsedPowerAutomateFlow) -> str:
    """Return a description of the flow for column lineage extraction.

    Power Automate flows move data between services rather than transforming
    database columns, so lineage is expressed as a service-to-service data
    transfer description rather than a column mapping.
    """
    parts = [
        f"Power Automate Flow: {flow.name}",
        f"Description: {flow.description or '(none)'}",
        f"Trigger: {flow.trigger_summary or '(none)'}",
        f"Connected services: {', '.join(flow.connections) or '(none)'}",
        "",
        "Actions (in declared order):",
    ]
    for action in flow.actions:
        conn_note = f" via {action.connection}" if action.connection else ""
        after_note = f" (runs after: {', '.join(action.run_after)})" if action.run_after else ""
        parts.append(f"  - {action.name} [{action.type}{conn_note}]{after_note}")
    return "\n".join(parts)


def _lineage_content_dataflow(dataflow: ParsedDataflow) -> str:
    """Return dataflow M-code for column lineage extraction."""
    parts = [
        f"Dataflow: {dataflow.name}",
        f"Description: {dataflow.description or '(none)'}",
        "",
        _MCODE_PREAMBLE,
        dataflow.all_mcode,
    ]
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Shared formatting helpers
# ---------------------------------------------------------------------------

def _meta_block(doc_type: str, path: Path) -> str:
    return textwrap.dedent(f"""\
        | | |
        | --- | --- |
        | **Type** | {doc_type} |
        | **Source file** | `{path.name}` |
        | **Generated** | {datetime.now().strftime('%Y-%m-%d')} |
    """)


def _depends_on_text(activity: PipelineActivity) -> str:
    if not activity.depends_on:
        return ""
    parts = []
    for dep in activity.depends_on:
        conditions = dep.conditions
        if not conditions or conditions == ["Succeeded"]:
            label = DEPENDENCY_CONDITION_LABELS["Succeeded"]
        else:
            labels = [DEPENDENCY_CONDITION_LABELS.get(c, c) for c in conditions]
            label = " or ".join(labels)
        parts.append(f"after {dep.activity_name} ({label})")
    return "; ".join(parts)


def _resolve_dataflow(
    activity: PipelineActivity,
    dataflow_map: dict[str, ParsedDataflow],
) -> ParsedDataflow | None:
    if activity.activity_type not in DATAFLOW_ACTIVITY_TYPES:
        return None
    props = activity.type_properties
    candidates = [
        props.get("dataflowId", ""),
        props.get("dataflow", {}).get("referenceName", "") if isinstance(props.get("dataflow"), dict) else "",
        activity.name,
    ]
    for candidate in candidates:
        if not candidate:
            continue
        stem = Path(candidate).stem
        if stem in dataflow_map:
            return dataflow_map[stem]
        for key, df in dataflow_map.items():
            if key.lower() == stem.lower():
                return df
    return None


def _resolve_notebook(
    activity: PipelineActivity,
    notebook_map: dict[str, ParsedNotebook],
) -> ParsedNotebook | None:
    if activity.activity_type not in ("TridentNotebook", "Notebook"):
        return None
    props = activity.type_properties
    candidates = [
        props.get("notebookId", ""),
        props.get("notebook", {}).get("referenceName", "") if isinstance(props.get("notebook"), dict) else "",
        activity.notebook_path or "",
        activity.name,
    ]
    for candidate in candidates:
        if not candidate:
            continue
        stem = Path(candidate).stem
        if stem in notebook_map:
            return notebook_map[stem]
        for key, nb in notebook_map.items():
            if key.lower() == stem.lower():
                return nb
    return None
