"""
Markdown documentation generator.

Every document — pipeline or orphan notebook — produces the same five sections:

  ## Purpose
  ## What It Does
  ## Relationships
  ## Business Goal
  ## Data Quality & Alerts

Each section is generated by a dedicated LLM call so context stays focused.
The content summary (_pipeline_content / _notebook_content) is built once and
reused across all five calls for the same document.
"""

from __future__ import annotations

import textwrap
from datetime import datetime
from pathlib import Path

from agent.ai.base_client import BaseLLMClient
from agent.ai.llm_client import _summarise_props
from agent.config import ACTIVITY_TYPE_LABELS, DEPENDENCY_CONDITION_LABELS
from agent.parsers.notebook_parser import ParsedNotebook
from agent.parsers.pipeline_parser import ParsedPipeline, PipelineActivity

SECTIONS = ["Purpose", "What It Does", "Flow", "Business Goal", "Data Quality & Alerts"]


# ---------------------------------------------------------------------------
# Public generators
# ---------------------------------------------------------------------------

def generate_pipeline_doc(
    pipeline: ParsedPipeline,
    notebook_map: dict[str, ParsedNotebook],
    client: BaseLLMClient,
) -> str:
    doc_group = pipeline.name
    c = _pipeline_contents(pipeline, notebook_map)

    parts = [
        f"# {pipeline.name}",
        _meta_block("Pipeline", pipeline.source_path),
        f"## Purpose\n\n{client.section_purpose(pipeline.name, c['purpose'], doc_group)}",
        f"## What It Does\n\n{client.section_what_it_does(pipeline.name, c['what'], doc_group)}",
        f"## Flow\n\n{client.section_flow(pipeline.name, c['relationships'], doc_group)}",
        f"## Business Goal\n\n{client.section_business_goal(pipeline.name, c['goal'], doc_group)}",
        f"## Data Quality & Alerts\n\n{client.section_data_quality(pipeline.name, c['quality'], doc_group)}",
        "\n---",
        f"*Documentation generated on {datetime.now().strftime('%Y-%m-%d')} "
        f"from `{pipeline.source_path.name}`.*",
    ]
    return "\n\n".join(parts)


def generate_notebook_doc(notebook: ParsedNotebook, client: BaseLLMClient) -> str:
    doc_group = notebook.name
    c = _notebook_contents(notebook)

    parts = [
        f"# {notebook.name}",
        _meta_block("Data Process", notebook.source_path),
        f"## Purpose\n\n{client.section_purpose(notebook.name, c['purpose'], doc_group)}",
        f"## What It Does\n\n{client.section_what_it_does(notebook.name, c['what'], doc_group)}",
        f"## Flow\n\n{client.section_flow(notebook.name, c['relationships'], doc_group)}",
        f"## Business Goal\n\n{client.section_business_goal(notebook.name, c['goal'], doc_group)}",
        f"## Data Quality & Alerts\n\n{client.section_data_quality(notebook.name, c['quality'], doc_group)}",
        "\n---",
        f"*Documentation generated on {datetime.now().strftime('%Y-%m-%d')} "
        f"from `{notebook.source_path.name}`.*",
    ]
    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# Public helper used by main.py
# ---------------------------------------------------------------------------

def get_linked_notebooks(
    pipeline: ParsedPipeline,
    notebook_map: dict[str, ParsedNotebook],
) -> set[str]:
    """Return the names of all notebooks linked to any activity in *pipeline*."""
    linked: set[str] = set()
    for activity in pipeline.activities:
        nb = _resolve_notebook(activity, notebook_map)
        if nb:
            linked.add(nb.name)
    return linked


# ---------------------------------------------------------------------------
# Section-specific content builders
# ---------------------------------------------------------------------------

def _pipeline_contents(
    pipeline: ParsedPipeline,
    notebook_map: dict[str, ParsedNotebook],
) -> dict[str, str]:
    """Return a dict of tailored content strings, one per document section."""
    ordered = pipeline.ordered_activities()
    activity_labels = [
        f"{a.name} ({ACTIVITY_TYPE_LABELS.get(a.activity_type, a.activity_type)})"
        for a in ordered
    ]
    description = pipeline.description or ""
    params = ", ".join(f"{p.name}" for p in pipeline.parameters) if pipeline.parameters else ""

    # Linked notebooks — name + section headings
    notebook_refs: list[str] = []
    for a in ordered:
        nb = _resolve_notebook(a, notebook_map)
        if nb:
            headings = ", ".join(s.heading for s in nb.sections)
            notebook_refs.append(f"{nb.name} (sections: {headings})")

    # Code from linked notebooks — for quality and what-it-does
    notebook_code = ""
    for a in ordered:
        nb = _resolve_notebook(a, notebook_map)
        if nb:
            notebook_code += nb.all_code[:1500] + "\n"

    # Control / fail / webhook activities — signal quality checks
    quality_activities = [
        f"{a.name} ({ACTIVITY_TYPE_LABELS.get(a.activity_type, a.activity_type)}): {_summarise_props(a.type_properties)}"
        for a in ordered
        if a.activity_type in ("IfCondition", "Fail", "WebHook", "Filter", "Until", "Switch")
    ]

    # External connections — bronze activities
    sources = [
        f"{a.name}: {_summarise_props(a.type_properties)}"
        for a in ordered
        if a.activity_type in ("Copy", "Web", "WebHook", "Lookup", "GetMetadata")
    ]

    return {
        "purpose": f"Pipeline: {pipeline.name}\nDescription: {description}\nSteps: {', '.join(activity_labels)}",
        "what": (
            f"Pipeline: {pipeline.name}\nDescription: {description}\n"
            f"Steps in order: {', '.join(activity_labels)}\n"
            + (f"Linked data processes: {'; '.join(notebook_refs)}\n" if notebook_refs else "")
            + (f"Code excerpt:\n{notebook_code[:2000]}" if notebook_code.strip() else "")
        ),
        "relationships": (
            f"Pipeline: {pipeline.name}\n"
            + (f"External data sources: {'; '.join(sources)}\n" if sources else "")
            + (f"Linked data processes: {'; '.join(notebook_refs)}\n" if notebook_refs else "")
            + (f"Input parameters: {params}\n" if params else "")
        ),
        "goal": f"Pipeline: {pipeline.name}\nDescription: {description}\nSteps: {', '.join(activity_labels)}",
        "quality": (
            f"Pipeline: {pipeline.name}\n"
            + (f"Control and error steps: {'; '.join(quality_activities)}\n" if quality_activities else "")
            + (f"Code excerpt:\n{notebook_code[:2000]}" if notebook_code.strip() else "")
        ),
    }


def _notebook_contents(notebook: ParsedNotebook) -> dict[str, str]:
    """Return a dict of tailored content strings, one per document section."""
    headings = ", ".join(s.heading for s in notebook.sections)
    description = notebook.description or ""
    code = notebook.all_code

    return {
        "purpose": f"Process: {notebook.name}\nDescription: {description}\nSections: {headings}",
        "what": (
            f"Process: {notebook.name}\nDescription: {description}\n"
            f"Sections: {headings}\nCode excerpt:\n{code[:3000]}"
        ),
        "relationships": (
            f"Process: {notebook.name}\nDescription: {description}\nSections: {headings}"
        ),
        "goal": f"Process: {notebook.name}\nDescription: {description}\nSections: {headings}",
        "quality": (
            f"Process: {notebook.name}\nSections: {headings}\n"
            f"Code excerpt:\n{code[:3000]}"
        ),
    }


# ---------------------------------------------------------------------------
# Shared formatting helpers
# ---------------------------------------------------------------------------

def _meta_block(doc_type: str, path: Path) -> str:
    return textwrap.dedent(f"""\
        | | |
        | --- | --- |
        | **Type** | {doc_type} |
        | **Source file** | `{path.name}` |
        | **Generated** | {datetime.now().strftime('%Y-%m-%d')} |
    """)


def _depends_on_text(activity: PipelineActivity) -> str:
    if not activity.depends_on:
        return ""
    parts = []
    for dep in activity.depends_on:
        conditions = dep.conditions
        if not conditions or conditions == ["Succeeded"]:
            label = DEPENDENCY_CONDITION_LABELS["Succeeded"]
        else:
            labels = [DEPENDENCY_CONDITION_LABELS.get(c, c) for c in conditions]
            label = " or ".join(labels)
        parts.append(f"after {dep.activity_name} ({label})")
    return "; ".join(parts)


def _resolve_notebook(
    activity: PipelineActivity,
    notebook_map: dict[str, ParsedNotebook],
) -> ParsedNotebook | None:
    if activity.activity_type not in ("TridentNotebook", "Notebook"):
        return None
    props = activity.type_properties
    candidates = [
        props.get("notebookId", ""),
        props.get("notebook", {}).get("referenceName", "") if isinstance(props.get("notebook"), dict) else "",
        activity.notebook_path or "",
        activity.name,
    ]
    for candidate in candidates:
        if not candidate:
            continue
        stem = Path(candidate).stem
        if stem in notebook_map:
            return notebook_map[stem]
        for key, nb in notebook_map.items():
            if key.lower() == stem.lower():
                return nb
    return None
